version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  redis:
    image: redis:latest
  worker:
    build:
      context: ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  server:
    build:
      context: ./server
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=fibo
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    build:
      context: ./client
    environment:
      - VITE_API_URL=http://host.docker.internal:5000
    ports:
      - 3000:3000
